modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "bbclient"
version="0.1-1.19.2"
logoFile="logo.PNG"
displayName="BBClient"
displayURL="https://www.bernhardbmx.net/mc/BBClient/"
authors="Ben G (BernhardBMX)"
credits="None"
description = '''
Supports Create and Optifine
'''

[[dependencies.bbclient]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bbclient]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "CLIENT"

#[[dependencies.bbclient]]
#modId = "optifine"
#mandatory = true
#versionRange = "[1.19.2,1.20)"
#ordering = "NONE"
#side = "CLIENT"
